### ISSUE TITLE
AutoML.Net improvements tracking down list

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#6145]
- AutoML Sweepable API (#5993)
  - [x] implementation (#6285)
  - [x] make it public (#6173)
  - [x] documents
    - [x] [sweepable pipeline](https://github.com/dotnet/machinelearning/pull/6218) 
  - [ ] code example
  - [x] jupyter notebook example
    - [forecast using ssa](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Forecasting%20using%20SSA%20with%20Luna%20Dataset.ipynb)
    - [automl sweepable api](https://github.com/dotnet/csharp-notebooks/pull/69#pullrequestreview-1119018464)

- AutoML Featurizer API (#6187)
  - [x] implementation (#6205) (#6261)
  - [x] make it public
  - [x] documents
  - [ ] code example
    - [x] image classification with image featurizer
  - [x] jupyter notebook example
    - [x] [regression with taxi fare](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Regression%20with%20Taxi%20Dataset.ipynb)
    - [x] [classification with titanic](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/REF-Kaggle%20with%20Titanic%20Dataset.ipynb)

   
- AutoML Experiment API (#6118 )
  - [x] implementation
  - [x] make it pubic (#6173)
  - [x] documents [#6589]
  - [ ] code example
  - [x] jupyter notebook example
    - [titanic](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/REF-Kaggle%20with%20Titanic%20Dataset.ipynb)
    -  [taxi-fare](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Regression%20with%20Taxi%20Dataset.ipynb)
    - [iris](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Classification%20with%20Iris%20Dataset.ipynb)
    - [luna forecasting using regression](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Forecasting%20using%20Regression%20with%20Luna%20Dataset.ipynb)
    - needs more
  - [ ] reimplement existing experiment using AutoML Experiment API
    - [x] BinaryExperiment (#6246)
    - [x] Multiclass Experiment (#6270)
    - [x] Regression (#6338)
    - [ ] Recommendation
    - [ ] Ranking

- AutoML Advance Feature
  - [x] continue training [#6335]
  - [x] exit strategy [#6402 ]
  - [x] limit resource (CPU/memory) [#6305]

**Comment by michaelgsharp** [comment]
@LittleLittleCloud I'll tag this for ML.NET 2.0 (For release this November) just so it can be tracked appropriately. If the plan is not to have it by Nov let me know And I can push it to a later milestone.
