### ISSUE TITLE
Improve Microsoft.ML.Tokenizers and drive complete 1.0 API

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#6984]
**Goal**: Enable .NET developers to use tokenizers in their data pre-processing pipelines as part of their embedding and token generation tasks using language models. 

- [ ] Add support for more commonly used Tokenizers
  - [ ] TikToken https://github.com/dotnet/machinelearning/pull/6981
  - [ ] WordPiece
  - [ ] SentencePiece
  - [ ] WordLevel
  - [ ] Unigram
  - [ ] Bert
- [ ] Measure and improve performance of Tokenizers API - making breaking changes where necessary. (https://github.com/dotnet/machinelearning/issues/6982)
- [ ] Explore existing construction patterns to improve usability - both in factory API and load from configuration.
- [ ] Drive adoption of Microsoft.ML.Tokenizers in other libraries
